### PR TITLE
Remove location model and fix some bugs

### LINKED ISSUE #13: Remove location model
-> lelylan/devices#64

### LINKED ISSUE #15: jobs.events isn't capped by default

### LINKED ISSUE #16: SOCKET_IO_LOG environment variables not found
Code: https://github.com/lelylan/websockets/blob/master/app.js#L5
Change SCOKET_IO_LOG to SOCKET_IO_LOG

### PR DESCRIPTION
**Pull request by FedeG**
Close #13 
Fix #15 
Fix #16

### CODE REVIEW

File: lib/loop.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ var Event        = require('../app/models/jobs/event')
 
 // find the valid tokens associated to property-udpated events
 exports.execute = function(io) {
+  Event.db.db.executeDbCommand({"convertToCapped": "events", size: 10000000, max:1000})
```
Comment (andreareginato) [inline lib/loop.js]: Same comment as made on physical micro-service
